version: '3.4'
services:
  reverse-proxy:
    image: traefik:maroilles
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    build: ./
    labels:
      - "traefik.frontend.rule=Host:doittest.localhost"
      - "traefik.port=8080"
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: doittest
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"